# Generated by Django 5.0.6 on 2024-10-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='contact',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='contact',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
